#!/usr/bin/env python


"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 1.0
 Generation time: Tue Mar 27 22:57:42 2007
   Source file: foot.tmpl
   Source file last modified: Tue Mar 27 22:55:32 2007
"""

__CHEETAH_genTime__ = 'Tue Mar 27 22:57:42 2007'
__CHEETAH_src__ = 'foot.tmpl'
__CHEETAH_version__ = '1.0'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class foot(Template):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        Template.__init__(self, *args, **KWs)

    def respond(self,
            trans=None,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName):


        """
        This is the main method generated by Cheetah
        """

        if not trans: trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        else: dummyTrans = False
        write = trans.response().write
        SL = self._searchList
        globalSetVars = self._globalSetVars
        filter = self._currentFilter
        
        ########################################
        ## START - generated method body
        
        if VFFSL(SL,"varExists",False)('offset'):
            write('    <div id="next-button">\r\n        <a href="index?offset=')
            __v = VFFSL(SL,"offset",True)
            if __v is not None: write(filter(__v, rawExpr='$offset')) # from line 3, col 31.
            write('">next ')
            __v = VFFSL(SL,"num_entries",True)
            if __v is not None: write(filter(__v, rawExpr='$num_entries')) # from line 3, col 45.
            write(''' &gt;&gt;</a>
        &nbsp; &nbsp;
    </div>
''')
        write('''	<!--<div id="footer"></div> Empty right now! -->
</div> <!-- end main content -->
<div id="right-menu">
<div id="navcontainer"> <!--begin side navigation -->
    <div id="logo">
        <img src="/static/billmill.gif">
    </div>
    <ul id="right-navlist">
        <li>
        <a href="/">blog</a> &bull;
        <a href="/code">code</a> &bull;
        <a href="http://flickr.com/photos/llimllib">photos</a> &bull;
        <a href="/Rss/">rss</a> &bull;
        <a href="http://www.last.fm/user/llimllib">music</a> &bull;
        <a href="http://del.icio.us/llimllib">bookmarks</a> &bull;
        <a href="http://bloglines.com/public/llimllib">blogroll</a> &bull;
        <a href="http://reddit.com/user/llimllib">reddit</a>&bull;
        <a href="mailto:bill.mill@gmail.com">email</a>
        </li>
    </ul>
</div><!-- end side navigaion -->

<!-- begin more info -->
<div id="more-info"><!--<h2 class="sideheader">My Name Rhymes</h2>-->
		<p></p>
		<p>I'm a programmer for a small company in 
        Baltimore, Maryland, USA. Besides programming, I play competitive 
        <a href="http://en.wikipedia.org/wiki/Ultimate_%28sport%29">ultimate</a>. 
        I blog at irregular intervals about various programming topics, but mostly
        Python.
        </p>
</div><!-- end more info -->

</div><!--end main box div-->
</body>
</html>
''')
        
        ########################################
        ## END - generated method body
        
        return dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    __str__ = respond

    _mainCheetahMethod_for_foot= 'respond'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    foot().runAsMainProgram()

