#!/usr/bin/env python


"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 1.0
 Generation time: Thu Jun 22 18:08:31 2006
   Source file: foot.tmpl
   Source file last modified: Wed Jun 21 10:09:58 2006
"""

__CHEETAH_genTime__ = 'Thu Jun 22 18:08:31 2006'
__CHEETAH_src__ = 'foot.tmpl'
__CHEETAH_version__ = '1.0'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class foot(Template):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        Template.__init__(self, *args, **KWs)

    def respond(self,
            trans=None,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName):


        """
        This is the main method generated by Cheetah
        """

        if not trans: trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        else: dummyTrans = False
        write = trans.response().write
        SL = self._searchList
        globalSetVars = self._globalSetVars
        filter = self._currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''
	<!--<div id="footer"></div> Empty right now! -->
</div> <!-- end main content -->
<div id="right-menu">
<div id="navcontainer"> <!--begin side navigation -->
    <div id="logo">
        <!--your logo could go here -->
    </div>
    <ul id="right-navlist">
        <li>
        <a href="#">code</a> &bull; 
        <a href="#">words</a> &bull;
        <a href="http://flickr.com/photos/llimllib">photos</a> &bull;
        <a href="/">blog</a> &bull;
        <a href="/Rss">rss</a> &bull;
        <a href="http://www.last.fm/user/llimllib">music</a> &bull;
        <a href="http://del.icio.us/llimllib">bookmarks</a> &bull;
        <a href="http://bloglines.com/public/llimllib">blogroll</a> &bull;
        <a href="mailto:bill.mill@gmail.com">email</a>
        </li>
    </ul>
</div><!-- end side navigaion -->

<!-- begin more info -->
<div id="more-info"><!--<h2 class="sideheader">My Name Rhymes</h2>-->
		<p></p>
		<p>I'm a programmer for a small company in 
        Connecticut, USA. Besides programming, I play competitive 
        <a href="http://www.ultimatehandbook.com/uh/basics_thegame.html">ultimate</a>. I blog
        at irregular intervals about various programming topics, but mostly
        Python.
        </p>
</div><!-- end more info -->

</div><!--end main box div-->
</body>
</html>
''')
        
        ########################################
        ## END - generated method body
        
        return dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    __str__ = respond

    _mainCheetahMethod_for_foot= 'respond'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    foot().runAsMainProgram()

