#!/usr/bin/env python


"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 1.0
 Generation time: Tue Mar 27 22:57:42 2007
   Source file: rss.tmpl
   Source file last modified: Sat Jan 20 01:06:17 2007
"""

__CHEETAH_genTime__ = 'Tue Mar 27 22:57:42 2007'
__CHEETAH_src__ = 'rss.tmpl'
__CHEETAH_version__ = '1.0'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class rss(Template):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        Template.__init__(self, *args, **KWs)

    def respond(self,
            trans=None,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName):


        """
        This is the main method generated by Cheetah
        """

        if not trans: trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        else: dummyTrans = False
        write = trans.response().write
        SL = self._searchList
        globalSetVars = self._globalSetVars
        filter = self._currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<?xml version="1.0" ?>
<rss version="2.0" xmlns:admin="http://webns.net/mvcb/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:creativeCommons="http://backend.userland.com/creativeCommonsRssModule" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:html="http://www.w3.org/1999/html" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:slash="http://purl.org/rss/1.0/modules/slash/">
    <channel>
        <title>''')
        __v = VFFSL(SL,"blog_title",True)
        if __v is not None: write(filter(__v, rawExpr='$blog_title')) # from line 4, col 16.
        write('</title>\r\n        <link>')
        __v = VFFSL(SL,"base_url",True)
        if __v is not None: write(filter(__v, rawExpr='$base_url')) # from line 5, col 15.
        write('</link>\r\n        <description>')
        __v = VFFSL(SL,"blog_desc",True)
        if __v is not None: write(filter(__v, rawExpr='$blog_desc')) # from line 6, col 22.
        write('</description>\r\n        <language>')
        __v = VFFSL(SL,"blog_lang",True)
        if __v is not None: write(filter(__v, rawExpr='$blog_lang')) # from line 7, col 19.
        write('</language>\r\n        <dc:creator>')
        __v = VFFSL(SL,"blog_author",True)
        if __v is not None: write(filter(__v, rawExpr='$blog_author')) # from line 8, col 21.
        write(' ')
        __v = VFFSL(SL,"blog_email",True)
        if __v is not None: write(filter(__v, rawExpr='$blog_email')) # from line 8, col 34.
        write('</dc:creator>\r\n        <admin:errorReportsTo rdf:resource="mailto:')
        __v = VFFSL(SL,"blog_email",True)
        if __v is not None: write(filter(__v, rawExpr='$blog_email')) # from line 9, col 52.
        write('"/>\r\n')
        for e in VFFSL(SL,"entries",True):
            write('        <item>\r\n            <title>')
            __v = VFFSL(SL,"e.title",True)
            if __v is not None: write(filter(__v, rawExpr='$e.title')) # from line 12, col 20.
            write('</title>\r\n            <guid isPermaLink="false">')
            __v = VFFSL(SL,"e.relpath",True)
            if __v is not None: write(filter(__v, rawExpr='$e.relpath')) # from line 13, col 39.
            write('</guid>\r\n            <link>')
            __v = VFFSL(SL,"e.link",True)
            if __v is not None: write(filter(__v, rawExpr='$e.link')) # from line 14, col 19.
            write('</link>\r\n            <description>')
            __v = VFFSL(SL,"e.desc",True)
            if __v is not None: write(filter(__v, rawExpr='$e.desc')) # from line 15, col 26.
            write('</description>\r\n            <content:encoded><![CDATA[')
            __v = VFFSL(SL,"e.text",True)
            if __v is not None: write(filter(__v, rawExpr='$e.text')) # from line 16, col 39.
            write(']]></content:encoded>\r\n            <category domain="')
            __v = VFFSL(SL,"base_url",True)
            if __v is not None: write(filter(__v, rawExpr='$base_url')) # from line 17, col 31.
            write('">')
            __v = VFFSL(SL,"e.relpath",True)
            if __v is not None: write(filter(__v, rawExpr='$e.relpath')) # from line 17, col 42.
            write('</category>\r\n            <dc:date>')
            __v = VFFSL(SL,"e.time",True)
            if __v is not None: write(filter(__v, rawExpr='$e.time')) # from line 18, col 22.
            write('</dc:date>\r\n        </item>\r\n')
        write('    </channel>\r\n</rss>\r\n')
        
        ########################################
        ## END - generated method body
        
        return dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    __str__ = respond

    _mainCheetahMethod_for_rss= 'respond'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    rss().runAsMainProgram()

