#!/usr/bin/env python


"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 1.0
 Generation time: Thu Jun 22 18:08:31 2006
   Source file: story.tmpl
   Source file last modified: Thu Jun 22 18:04:44 2006
"""

__CHEETAH_genTime__ = 'Thu Jun 22 18:08:31 2006'
__CHEETAH_src__ = 'story.tmpl'
__CHEETAH_version__ = '1.0'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class story(Template):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        Template.__init__(self, *args, **KWs)

    def respond(self,
            trans=None,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName):


        """
        This is the main method generated by Cheetah
        """

        if not trans: trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        else: dummyTrans = False
        write = trans.response().write
        SL = self._searchList
        globalSetVars = self._globalSetVars
        filter = self._currentFilter
        
        ########################################
        ## START - generated method body
        
        for e in VFFSL(SL,"entries",True):
            write('    <div id="entry">\n    <h1>')
            __v = VFFSL(SL,"e.title",True)
            if __v is not None: write(filter(__v, rawExpr='$e.title')) # from line 3, col 9.
            write('\n    <br>')
            __v = VFFSL(SL,"e.tmstr",True)
            if __v is not None: write(filter(__v, rawExpr='$e.tmstr')) # from line 4, col 9.
            write('</h1><br>\n    ')
            __v = VFFSL(SL,"e.text",True)
            if __v is not None: write(filter(__v, rawExpr='$e.text')) # from line 5, col 5.
            write('\n    <p>\n')
            if VFFSL(SL,"varExists",False)('e.n_comments'):
                write('')
                if VFFSL(SL,"e.n_comments",True) > 1:
                    write('')
                    commentstr = ' (%s Comments)' % (VFFSL(SL,"e.n_comments",True))
                    write('')
                elif VFFSL(SL,"e.n_comments",True) == 1:
                    write('')
                    commentstr = ' (1 Comment)'
                    write('')
                else:
                    write('')
                    commentstr = ' (0 Comments)'
                    write('')
                write('')
            else:
                write('')
                commentstr = ''
                write('')
            write('    [<a href="')
            __v = VFFSL(SL,"e.relpath",True)
            if __v is not None: write(filter(__v, rawExpr='$e.relpath')) # from line 18, col 15.
            write('">#')
            __v = VFFSL(SL,"commentstr",True)
            if __v is not None: write(filter(__v, rawExpr='$commentstr')) # from line 18, col 28.
            write('</a>]  ')
            __v = VFFSL(SL,"getVar",False)('e.keywords', 'bluck')
            if __v is not None: write(filter(__v, rawExpr="$getVar('e.keywords', 'bluck')")) # from line 18, col 46.
            write('\n    ')
            __v = VFFSL(SL,"getVar",False)('e', 'glarg')
            if __v is not None: write(filter(__v, rawExpr="$getVar('e', 'glarg')")) # from line 19, col 5.
            write('\n    </div>\n')
        
        ########################################
        ## END - generated method body
        
        return dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    __str__ = respond

    _mainCheetahMethod_for_story= 'respond'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    story().runAsMainProgram()

