#!/usr/bin/env python


"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 1.0
 Generation time: Tue Mar 27 22:57:42 2007
   Source file: story.tmpl
   Source file last modified: Sat Jan 20 01:06:17 2007
"""

__CHEETAH_genTime__ = 'Tue Mar 27 22:57:42 2007'
__CHEETAH_src__ = 'story.tmpl'
__CHEETAH_version__ = '1.0'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class story(Template):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        Template.__init__(self, *args, **KWs)

    def respond(self,
            trans=None,
            VFFSL=valueFromFrameOrSearchList,
            VFN=valueForName):


        """
        This is the main method generated by Cheetah
        """

        if not trans: trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        else: dummyTrans = False
        write = trans.response().write
        SL = self._searchList
        globalSetVars = self._globalSetVars
        filter = self._currentFilter
        
        ########################################
        ## START - generated method body
        
        write('    <div id="entry">\r\n    <h1>')
        __v = VFFSL(SL,"title",True)
        if __v is not None: write(filter(__v, rawExpr='$title')) # from line 2, col 9.
        write('\r\n<br>')
        __v = VFFSL(SL,"tmstr",True)
        if __v is not None: write(filter(__v, rawExpr='$tmstr')) # from line 3, col 5.
        write('</h1><br>\r\n')
        __v = VFFSL(SL,"text",True)
        if __v is not None: write(filter(__v, rawExpr='$text')) # from line 4, col 1.
        write('\r\n<p>\r\n')
        if VFFSL(SL,"varExists",False)('n_comments'):
            write('')
            if VFFSL(SL,"n_comments",True) > 1:
                write('')
                commentstr = ' (%s Comments)' % (VFFSL(SL,"n_comments",True))
                write('')
            elif VFFSL(SL,"n_comments",True) == 1:
                write('')
                commentstr = ' (1 Comment)'
                write('')
            else:
                write('')
                commentstr = ' (0 Comments)'
                write('')
        else:
            write('')
            commentstr = ''
        write('[<a href="')
        __v = VFFSL(SL,"base_url",True)
        if __v is not None: write(filter(__v, rawExpr='$base_url')) # from line 17, col 11.
        __v = VFFSL(SL,"relpath",True)
        if __v is not None: write(filter(__v, rawExpr='$relpath')) # from line 17, col 20.
        write('">#')
        __v = VFFSL(SL,"commentstr",True)
        if __v is not None: write(filter(__v, rawExpr='$commentstr')) # from line 17, col 31.
        write('</a>] ')
        __v = VFFSL(SL,"getVar",False)('keywords', '')
        if __v is not None: write(filter(__v, rawExpr="$getVar('keywords', '')")) # from line 17, col 48.
        write('\r\n</div>\r\n')
        
        ########################################
        ## END - generated method body
        
        return dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    __str__ = respond

    _mainCheetahMethod_for_story= 'respond'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    story().runAsMainProgram()

